typography_spectrum: 0.9081041226163507
color:
  brandStrength: 0.9977277384605259
  lightness: 0.2575402574148029
  saturation: 0.6817872319370508
  rhythmicContrast: 0.527365610934794
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
layout_spectrum: 0.0770900584757328
name: Mental Toughness Research Institute
title: Mental Toughness Profile  & Mental Toughness Coach Certification
